services:
  database:
    build: ./backend/database
    container_name: mongo_database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    logging:
      driver: "none"

  api:
    build: ./backend/api
    container_name: api
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: database
    depends_on:
      - database
    volumes:
      - ./backend/api:/app

volumes:
  mongo_data:
